In [371]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split

In [372]:
df = pd.read_csv('spam.csv')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [373]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [374]:
x = df[['v2']]
y = df['v1']

In [375]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,train_size=0.8)

In [376]:
xtrain

                                                     v2
1978  No I'm in the same boat. Still here at my moms...
3989  (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
3935     They r giving a second chance to rahul dengra.
4078     O i played smash bros  &lt;#&gt;  religiously.
4086  PRIVATE! Your 2003 Account Statement for 07973...
...                                                 ...
3772  I came hostel. I m going to sleep. Plz call me...
5191                             Sorry, I'll call later
5226      Prabha..i'm soryda..realy..frm heart i'm sory
5390                         Nt joking seriously i told
860                 In work now. Going have in few min.

[4457 rows x 1 columns]

In [385]:
vectorizer = CountVectorizer(stop_words='english',binary=True,min_df=1,max_df=1.0,max_features=100,ngram_range=(2,2))

vectors = vectorizer.fit_transform(xtrain['v2']) #[['v2']] => 'v2' => 1

In [386]:
vectorizer.stop_words

'english'

In [387]:
vectors.toarray() #7428

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 100))

In [388]:
vectorizer.get_feature_names_out()

array(['1000 cash', '10p min', '150p msg', '1st week', '2000 prize',
       '20p min', '2lands row', '2nd attempt', '86688 150p',
       'account statement', 'attempt contact', 'await collection',
       'bonus caller', 'caller prize', 'cash await', 'chance win',
       'claim code', 'claim ur', 'customer service', 'dating service',
       'decimal gt', 'don know', 'dont know', 'double mins', 'draw shows',
       'dun wan', 'free entry', 'good afternoon', 'good day',
       'good morning', 'good night', 'gt lt', 'gt min', 'gud ni8',
       'half price', 'happy birthday', 'happy new', 'hg suite342',
       'hope having', 'http www', 'identifier code', 'just got',
       'just text', 'just txt', 'land line', 'let know', 'like lt',
       'line claim', 'line rental', 'live operator', 'll later',
       'lt decimal', 'lt gt', 'mobile number', 'music 87066',
       'national rate', 'new year', 'nice day', 'ntt po', 'ok lor',
       'phone right', 'pick phone', 'pls send', 'po box', 'prize claim',
       'prize guaranteed', 'reply stop', 'right pls', 'row w1j6hl',
       'sae cs', 'selected receive', 'send message', 'send stop',
       'shows won', 'sms ac', 'sorry ll', 'speak live', 'suite342 2lands',
       'tell ur', 'text yes', 'thats cool', 'tone ur', 'trying contact',
       'ts cs', 'txt nokia', 'txt stop', 'txt word', 'ur awarded',
       'ur friends', 'ur mob', 'ur mobile', 'urgent mobile',
       'urgent trying', 'valid 12hrs', 've got', 'want come', 'wat time',
       'watching tv', 'week just', 'won 000'], dtype=object)